Re-adding changes to curry2read.  The changes fall into two categories: 1) allow curry2read to accept an option -q that silences chatter and 2) ensure that when an error occurs, the message identifies the tool as "curry2read", and the program prints the message to stderr, and exits with a status of 1.  These changes are needed for when scc invokes curry2read as a subprocess.

diff --git a/runtime/cmc/translator/bin/curry2read b/runtime/cmc/translator/bin/curry2read
--- a/runtime/cmc/translator/bin/curry2read
+++ b/runtime/cmc/translator/bin/curry2read
@@ -3,23 +3,31 @@
 BASEDIR=$(dirname $(dirname $(readlink -f $0)))
 # echo $BASEDIR
 
-if [ "$1" = "" ]
+QUIET=''
+if [ "$1" == "-q" ]
 then
-  echo Warning: no file given
-  exit
+  QUIET='-q'
+  shift
+fi
+
+if [ "$*" = "" ]
+then
+  echo `basename $0`: no input file. 1>&2
+  exit 1
 fi
 
 FILE=$(dirname $1)/$(basename $1 ".curry")
 if [ ! -f $FILE.curry ]
 then
-  echo Error: \"$FILE.curry\" not found
-  exit
+  echo `basename $0`: \"$FILE.curry\" not found. 1>&2
+  exit 1
 fi
 
-parsecurry --flat $FILE
-if [ $? = 0 ]
-   then echo parsed
-   else echo parse error ; exit
+parsecurry --flat $QUIET $FILE
+if [ $? -ne 0 ]
+then
+  echo `basename $0`: error parsing \"$FILE.curry\". 1>&2
+  exit 1
 fi
 
 # ------------------------------------------------------------------
@@ -35,19 +43,30 @@ TARGET=$(dirname $1)/.curry/$(basename $1 ".curry")
 
 if [ -f $TARGET.read -a $TARGET.read -nt $FILE.curry ]
 then
-  echo \"read\" up to date
+  if [ -z "$QUIET" ]
+  then
+    echo \"read\" up to date
+  fi
 else
   rm -f $FILE.read 
   # command="pakcs -Dkeepfiles=yes :set v3 :set args $FILE :load $BASEDIR/icurry/Main.curry :eval main :quit"
-  command="pakcs -q :set args $FILE :load $BASEDIR/icurry/Main.curry :eval Main.main :quit"
-  echo CURRYPATH $CURRYPATH
-  echo Running $command
-  $command
+  command="pakcs $QUIET :set args $FILE :load $BASEDIR/icurry/Main.curry :eval Main.main :quit"
+
+  if [ -n "$QUIET" ]
+  then
+    $command > /dev/null
+  else
+    echo CURRYPATH $CURRYPATH
+    echo Running $command
+    $command
+  fi
+
   if [ -f $FILE.read ]
-  then echo \"read\" file created
-       mv -f $FILE.icur $TARGET.icur
-       mv -f $FILE.read $TARGET.read
-  else echo Fail to create  \"$FILE.read\" file
-       exit 1
+  then
+    mv -f $FILE.icur $TARGET.icur
+    mv -f $FILE.read $TARGET.read
+  else
+    echo `basename $0`: failed to create \"$FILE.read\". 2>&1
+    exit 1
   fi
 fi
